language: node_js
node_js:
  - "9.11.2"
branches:
  only:
    - master
before_script:
  - npm i
script:
  - npm run build
sudo: false
addons:
  apt:
    packages:
    - lftp
os: linux
script: deploy.sh
