language: node_js
sudo: false
addons:
  apt:
    packages:
    - lftp
os: linux
node_js:
  - "9.11.2"
branches:
  only:
    - master
before_script:
  - npm i
script:
  - npm run build
  - bash deploy.sh
