language: node_js
node_js:
  - "9.11.2"
branches:
  only:
    - master
before_script:
  - npm i
script:
  - npm run build
before_deploy:
  - cd dist
after_success:
  "find dist -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://joduplessis.com/{} \\;"
