language: node_js
sudo: false
addons:
  apt:
    packages:
    - lftp
os: linux
node_js:
  - "9.11.2"
branches:
  only:
    - master
before_script:
  - npm i
script:
  - npm run build
  - lftp -u $FTP_USER,$FTP_PASSWORD $FTP_HOST -e "mirror -R -p ./dist/ public_html ; quit"
